import { MapLocation } from "models/MapLocation";

/**
 * Takes a MapLocation object, and template text with placeholders of {{[property]}}
 * and returns string with replaced properties found in MapLocation
 * @param mapLocation - a MapLocation object
 * @param text - template text with {{}} surrounding desired property names for replacments
 * @returns - string with replacements
 */
export function replacePlaceHolders(mapLocation: MapLocation, text: string): string{
    type ValidType = string | number | string[];
    /**
     * Takes a MapLocation and key (e.g. type, lat or lon) and returns MapLocation[property]
     * @param mapLocation - a MapLocation object
     * @param key - key in MapLocation object
     * @returns - property in MapLocation at specified key
     */
    function getProperty<MapLocation, K extends keyof MapLocation>(mapLocation: MapLocation, key: K): ValidType{
        return mapLocation[key] as ValidType;
    }

    /**
     * Looks up match property in provided mapLocation and returns string with value in MapLocation
     * @param match - match generated by regex expression search
     * @param mapLocation - a MapLocation object
     * @returns returns a string with match being replaced by property from mapLocation
     */
    function lookupReplacement (match: string, mapLocation: MapLocation): string{
        const cleanString = match.replace(/\{|\}/g,'');
        return getProperty(mapLocation, cleanString as keyof MapLocation) as string;
    }
    
    return text.replace(/\{\{.*\}\}/g,(match) => lookupReplacement(match, mapLocation))
}